### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by luky1300** [luky1300/fluffy-memory#2]

**Comment by Iskak83** [comment]
TODO:

* Create Navbar  component in Components folder
* Create Navbar.css file in style folder

**Comment by Iskak83** [comment]
DONE:
* Created Navbar component in Components folder
* Created Navbar.css file in style folder
* Created Jumbotron folder inside of img folder
* Added logo-defualt-191x52.png image file into Jumbotron folder

**Comment by Iskak83** [comment]
Done
