### ISSUE TITLE
Create Latest Blog Posts

### ISSUE THREAD

**Issue by luky1300** [luky1300/fluffy-memory#9]

**Comment by bluecollarcoders** [comment]
Added Latest blog section

**Comment by Iskak83** [comment]
we are getting the following error message on the console:
Warning: Invalid DOM property `datetime`. Did you mean `dateTime`?
    at time
    at div
    at a
    at article
    at div
    at div
    at section
    at LatestBlog
    at div
    at App

Warning: Invalid DOM property `class`. Did you mean `className`, (line 27)?
    at div
    at section
    at LatestBlog
    at div
    at App

**Comment by bluecollarcoders** [comment]
I didn't  get that error message.  I'll  change it later. Or you can just
edit out since it's  merged.
